version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: system-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ${VOLUME_DATA_PATH}:/var/lib/mysql
      - ${VOLUME_CONF_PATH}:/etc/mysql/conf.d
